routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('index.index');
Route::get('/category/{category}', 'IndexController@filter')->name('filter');

Route::get('/profile', 'IndexController@profileGet')->name('profile.get');
Route::get('/profile/edit', 'IndexController@profileEdit')->name('profile.edit');
Route::post('/profile/post', 'IndexController@profilePost')->name('profile.post');

Route::post('/profile/payFactor', 'IndexController@payFactor')->name('pay.factor');

Route::get('/ticketGet', 'IndexController@ticketGet')->name('ticket.get');
Route::post('/ticketPost', 'IndexController@ticketPost')->name('ticket.post');
Route::get('/answerTicket/{ticket}', 'TicketController@answerTicket')->name('answer.ticket');
Route::post('/answerTicket', 'TicketController@answerTicketPost')->name('answer.ticket.post');

Route::get('post/{post}', 'IndexController@showAPost');

Route::get('upload', 'UploadController@uploadGet')->name('upload.get');
Route::post('upload', 'UploadController@uploadPost')->name('upload.post');

Route::post('addToBasket/{id}', 'IndexController@addToBasket')->name('add.to.basket');
Route::post('removeFromBasket/{id}', 'IndexController@removeFromBasket')->name('remove.from.basket');

Route::get('checkOut', 'IndexController@checkOut')->name('check.out');

Route::get('shoppingCart', 'IndexController@shoppingCart')->name('shopping.cart');

Route::get('loginOrRegister', 'IndexController@loginOrRegister')->name('login.or.register');

Route::post('commentStoreSec', 'CommentController@storesec')->name('comment.store.sec');

Route::post('profile/increaseBalance', 'IndexController@increaseBalancePost')->name('increase.balance.post');
Route::get('profile/increaseBalance', 'IndexController@increaseBalanceGet')->name('increase.balance.get');

Route::get('profile/show/', 'IndexController@profile')->name('user.profile');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('products', 'ProductController');
Route::resource('users', 'UserController');
Route::resource('factors', 'FactorController');
Route::resource('categories', 'CategoryController');
Route::resource('tags', 'TagController');
Route::resource('comments', 'CommentController');
Route::resource('posts', 'PostController');
Route::resource('tickets', 'TicketController');

Route::get('{product}', 'IndexController@showProduct')->name('show.product.page');

resources/views/index/checkOut.blade.php
@extends('layouts.index')
@section('header')
    {{--    <link href="{{asset('css/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">--}}
    <link rel="stylesheet" href="{{ asset("bower_components/bootstrap/dist/css/bootstrap.min.css") }}">
    {{--    <link href="{{asset('css/bootstrap/css/bootstrap-responsive.min.css')}}" rel="stylesheet">--}}
    {{--<link href="{{asset('css/bootstrap/css/bootstrap-responsive-rtl.min.css')}}" rel="stylesheet">--}}
    <link rel="stylesheet" href="{{ asset("bower_components/bootstrap-rtl/dist/css/bootstrap-rtl.min.css") }}">
@endsection
@section('content')

    <div> فاکتور فروش:</div>
    <hr>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>عنوان</th>
            <th>قیمت</th>
            <th>تخفیف</th>
        </tr>
        </thead>
        <tbody>
        @foreach($products as $product)
            <tr>
                <td>{{ $product->title }}</td>
                <td>{{ $product->price }}</td>
                <td>{{ $product->discount }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
    <button class="cusmo-btn narrow pull-right" type="submit">
        مجموع
        :
        {{ $sum-$discount }}
        تومان
        <br>
        برای پرداخت کلیک کنید
    </button>

@endsection

resources/views/index/increaseBalance.blade.php
@extends('layouts.index')
@section('header')
    {{--    <link href="{{asset('css/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">--}}
    <link rel="stylesheet" href="{{ asset("bower_components/bootstrap/dist/css/bootstrap.min.css") }}">
    {{--    <link href="{{asset('css/bootstrap/css/bootstrap-responsive.min.css')}}" rel="stylesheet">--}}
    {{--<link href="{{asset('css/bootstrap/css/bootstrap-responsive-rtl.min.css')}}" rel="stylesheet">--}}
    <link rel="stylesheet" href="{{ asset("bower_components/bootstrap-rtl/dist/css/bootstrap-rtl.min.css") }}">
@endsection
@section('content')

    {!! Form::open(['route'=>['increase.balance.post', 'id' => Auth::user()->id ], 'method' => 'post' ]) !!}

    <!-- فیلد مبلغی که میخواهید حساب شما افزایش پیدا کند را بنویسید: -->
    <div class="form-group {{ $errors->has('amount') ? ' has-error' : '' }}">
        {!! Form::label('amount', 'مبلغی که میخواهید حساب شما افزایش پیدا کند را بنویسید:') !!}
        {!! Form::text('amount', null, ['class' => 'form-control']) !!}
        @if ($errors->has('amount'))
            <span class="help-block"><strong>{{ $errors->first('amount') }}</strong></span>
        @endif
    </div>

    <button class="btn btn-success">افزاش موجودی</button>
    {!! Form::close() !!}

@endsection

resources/views/index/index.blade.php
@extends('layouts.index')
@section('header')
    <link href="{{asset('css/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
    {{--    <link rel="stylesheet" href="{{ asset("bower_components/bootstrap/dist/css/bootstrap.min.css") }}">--}}
    <link href="{{asset('css/bootstrap/css/bootstrap-responsive.min.css')}}" rel="stylesheet">
    {{--<link href="{{asset('css/bootstrap/css/bootstrap-responsive-rtl.min.css')}}" rel="stylesheet">--}}
    <link rel="stylesheet" href="{{ asset("bower_components/bootstrap-rtl/dist/css/bootstrap-rtl.min.css") }}">
@endsection
@section('content')

    <div class="wrapper">

        @include('partials.header')


        @include('partials.mainSlider')


        @include('partials.mainItems')


{{--        @include('partials.footer')--}}


        @include('partials.copyright')


    </div>


@endsection
@push('scripts')
    <script>
        $('.pagination li').addClass('page-item');
        $('.pagination li a').addClass('page-link').addClass('btn btn-primary');
        $('.pagination span').addClass('page-link').addClass('btn btn-primary');
    </script>
@endpush

resources/views/index/loginRegister.blade.php
@extends('layouts.index')
@section('header')
    <link href="{{asset('css/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
    {{--<link rel="stylesheet" href="{{ asset("bower_components/bootstrap/dist/css/bootstrap.min.css") }}">--}}
    <link href="{{asset('css/bootstrap/css/bootstrap-responsive.min.css')}}" rel="stylesheet">
    {{--<link href="{{asset('css/bootstrap/css/bootstrap-responsive-rtl.min.css')}}" rel="stylesheet">--}}
    <link rel="stylesheet" href="{{ asset("bower_components/bootstrap-rtl/dist/css/bootstrap-rtl.min.css") }}">
@endsection
@section('content')

    <section class="section-checkout">
        <div class="container">

            <div class="phase-title current">
                <h1>برای خرید ابتدا ثبت نام کنید یا وارد شوید.</h1>
            </div>

            <div class="row-fluid">
                <div class="span6">
                    <div class="form-holder right-border">
                        <h4>ورود</h4>
                        <p>
                            در صورتی که در این وبسایت قبلا ثبت نام کرده اید یوزرنیم و پسورد خود را وارد کنید.
                        </p>
                        {!! Form::open(['route'=>['login' ], 'method' => 'post' ]) !!}
                        <div class="control-group">

                            <div class="controls">
                                <div class="form-label ">ایمیل</div>

                                <input type="text" id="email" name="email" class="required span12 cusmo-input"/>

                            </div>
                        </div>

                        <div class="control-group">

                            <div class="controls">
                                <div class="form-label ">رمز عبور</div>

                                <input id="password" type="password" name="password"
                                       class="required span12 cusmo-input"/>

                            </div>
                        </div>
                        <div class="rememberme">
                            <input type="checkbox" class="iCheck"> مرا به خاطر بسپار
                        </div>
                        <div class="forget-password">
                            <a href="#">رمز خود را فراموش کرده اید؟</a>
                        </div>
                        <div class="button-holder">
                            <button class="cusmo-btn narrow " type="submit">ورود</button>
                        </div>
                        {!! Form::close() !!}
                    </div>

                </div>
                <div class="span6">
                    <div class="form-holder">
                        <h4>ثبت نام</h4>
                        <p>
                            همین حالا ثبت نام کنید.ثبت نام شما کمتر از 30 ثانیه وقت شما را میگیرد.
                        </p>
                        {!! Form::open(['route'=>['register' ], 'method' => 'post' ]) !!}
                        <div class="control-group">

                            <div class="controls">
                                <div class="form-label ">نام</div>

                                <input type="text" name="name" class="required span12 cusmo-input"/>

                            </div>

                            <div class="controls">
                                <div class="form-label ">ایمیل</div>

                                <input type="text" name="email" class="required span12 cusmo-input"/>

                            </div>
                        </div>

                        <div class="control-group">

                            <div class="controls">
                                <div class="form-label ">رمز عبور</div>

                                <input type="password" name="password" class="required span12 cusmo-input"/>

                            </div>
                        </div>
                        <div class="control-group">

                            <div class="controls">
                                <div class="form-label ">تکرار رمز عبور</div>

                                <input type="password" name="password_confirmation" class="required span12 cusmo-input"/>

                            </div>
                        </div>
                        <button class="cusmo-btn narrow pull-right" type="submit">ثبت نام</button>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
            <div class="disabled-phases">
                <div class="phase-title">
                    <h1><a href="checkout-2.html">پرداخت</a></h1>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/index/shoppingCart.blade.php
@extends('layouts.index')
@section('header')
{{--    <link href="{{asset('css/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">--}}
        <link rel="stylesheet" href="{{ asset("bower_components/bootstrap/dist/css/bootstrap.min.css") }}">
{{--    <link href="{{asset('css/bootstrap/css/bootstrap-responsive.min.css')}}" rel="stylesheet">--}}
    {{--<link href="{{asset('css/bootstrap/css/bootstrap-responsive-rtl.min.css')}}" rel="stylesheet">--}}
    <link rel="stylesheet" href="{{ asset("bower_components/bootstrap-rtl/dist/css/bootstrap-rtl.min.css") }}">
@endsection
@section('content')

{{--    @include('partials.header')--}}
@include('partials.miniHeader')

    <section class="section-shopping-cart">
        <div class="container">
            <div class="row-fluid">

                <div class="span12">
                    <div class="page-content shopping-cart-page ">

                        @if($products != '')

                            <table class="table ">
                                <thead>
                                <tr>
                                    <th class="span2">تصویر</th>
                                    <th class="span5">نام محصول</th>
                                    {{--<th class="span2">تعداد</th>--}}
                                    <th class="span2 price-column" style="min-width: 100px">قیمت</th>
                                    <th class="span2 price-column" style="min-width: 100px">تخفیف</th>
                                    <th class="span1 price-column" style="min-width: 100px">جمع</th>
                                    <th class="span2">&nbsp;</th>
                                </tr>
                                </thead>
                                <tbody>

                                @foreach($products as $product)
                                    <tr>
                                        <td>
                                            <div class="thumb">
                                                <img alt="" src="{{ $product->image_main }}" width="100px" height="100px"/>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="desc">
                                                <h3>{{ $product->title }}</h3>
                                                <div class="tag-line">
                                                    {{ $product->description }}
                                                </div>
                                                <div class="pid">کد محصول: {{ $product->id }}</div>
                                            </div>
                                        </td>
                                        {{--<td>--}}
                                        {{--<div class="quantity">--}}
                                        {{--<select class="chosen-select">--}}
                                        {{--<option value="1">1</option>--}}
                                        {{--<option value="2">2</option>--}}
                                        {{--<option value="3">3</option>--}}
                                        {{--<option value="4">4</option>--}}
                                        {{--<option value="5">5</option>--}}
                                        {{--<option value="6">6</option>--}}
                                        {{--<option value="7">7</option>--}}
                                        {{--<option value="8">8</option>--}}
                                        {{--<option value="9">9</option>--}}

                                        {{--</select>--}}
                                        {{--</div>--}}
                                        {{--</td>--}}
                                        <td>
                                            <div class="price">
                                                {{ $product->price }}
                                            </div>
                                        </td>
                                        <td>
                                            <div class="price">
                                                {{ $product->discount }}
                                            </div>
                                        </td>
                                        <td>
                                            <div class="price">
                                                {{ ($product->price)-($product->discount) }}
                                            </div>
                                        </td>
                                        {!! Form::open(['route'=>['remove.from.basket', $product->id ], 'method' => 'post' ]) !!}
                                        <td>
                                            <div>
                                                {{--<div class="delete">--}}
                                                {{--class="close-btn"--}}
                                                <button type="submit" class="btn-danger btn">حذف</button>
                                            </div>
                                        </td>
                                        {!! Form::close() !!}
                                    </tr>
                                @endforeach

                                </tbody>
                            </table>

                            <div class="buttons-holder">
                                <a class="cusmo-btn gray narrow" href="{{ route('index.index') }}">اضافه کردن محصولات
                                    دیگر</a>
                                <a class="cusmo-btn narrow" href="{{ route('check.out') }}">تکمیل فرایند خرید</a>
                            </div>


                        @else
                            <div> هیچ محصولی در سبد شما وجود ندارد.</div>
                            <div class="buttons-holder pull-right">
                                <a class="cusmo-btn gray narrow" href="{{ route('index.index') }}">بازگشت</a>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </section>

    {{--@include('partials.footer')--}}
@include('partials.miniFooter')

@endsection

resources/views/index/showAPost.blade.php
@extends('layouts.index')
@section('header')
    <link href="{{asset('css/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
    {{--    <link rel="stylesheet" href="{{ asset("bower_components/bootstrap/dist/css/bootstrap.min.css") }}">--}}
    <link href="{{asset('css/bootstrap/css/bootstrap-responsive.min.css')}}" rel="stylesheet">
    {{--<link href="{{asset('css/bootstrap/css/bootstrap-responsive-rtl.min.css')}}" rel="stylesheet">--}}
    <link rel="stylesheet" href="{{ asset("bower_components/bootstrap-rtl/dist/css/bootstrap-rtl.min.css") }}">
@endsection
@section('content')
    <div>
        @include('partials.header')
    </div>
    <div class="container" style="margin-top: 80px ">

        <div style="font-size: xx-large;padding-top: 30px;padding-bottom: 30px;color: #000;">{{$post->title}}</div>
        <div>{!! $post->text !!}</div>

    </div>
    <div style="height: 70px"></div>
    <div class="clearfix"></div>
    <div>
        @include('partials.footer')
    </div>
    <div class="clearfix"></div>
    <div>
        @include('partials.copyright')
    </div>
@endsection

resources/views/index/showTickets.blade.php
@extends('layouts.index')
@section('header')
    {{--    <link href="{{asset('css/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">--}}
    <link rel="stylesheet" href="{{ asset("bower_components/bootstrap/dist/css/bootstrap.min.css") }}">
    {{--    <link href="{{asset('css/bootstrap/css/bootstrap-responsive.min.css')}}" rel="stylesheet">--}}
    {{--<link href="{{asset('css/bootstrap/css/bootstrap-responsive-rtl.min.css')}}" rel="stylesheet">--}}
    <link rel="stylesheet" href="{{ asset("bower_components/bootstrap-rtl/dist/css/bootstrap-rtl.min.css") }}">
    <style>
        #user_name {
            float: right;
            background-color: #b4d6ff;
            border-radius: .4em;
            padding: 3px 10px 10px 10px;
        }

        #user_message {
            min-width: 100px;
            max-width: 543px;
            background-color: #b4d6ff;
            border-radius: .4em;
            margin: 25px 0px 0px 0px;
            padding: 5px;
            float: right;
        }

        #support_name {
            float: left;
            background-color: #bcff78;
            border-radius: .4em;
            padding: 3px 10px 10px 10px;
        }

        #support_message {
            min-width: 100px;
            min-height: 50px;
            max-width: 543px;
            background-color: #bcff78;
            border-radius: .4em;
            margin: 25px 0px 0px 0px;
            padding: 5px;
            float: left;
        }
    </style>
@endsection
@section('content')
    <div>
        @include('partials.miniHeader')
    </div>
    <div class="container" style="margin-top: 80px;max-width: 700px ">

        @if(isset($tickets))
            <div id="user_name">{!! $firstTicket->user->name !!}</div>
            <div id="user_message">{!! $firstTicket->text !!}</div>

            <div class="clearfix"></div>
            @foreach($tickets as $ticket)
                @php
                    if ($ticket->user_id == Auth::user()->id){
                        $id_name = 'user_name';
                        $id_message = 'user_message';
                    }else{
                        $id_name = 'support_name';
                        $id_message = 'support_message';
                    }
                @endphp
                <div id="{{$id_name}}">{!! $ticket->user->name !!} </div>
                <div id="{{$id_message}}">
                    {!! $ticket->text !!}
                    <br><span style="color: gray; font-size: xx-small">{{$ticket->created_at}}</span>
                </div>
                <div class="clearfix"></div>
                <hr>
            @endforeach
        @endif

        <div id="myDiv"></div>

        @include('flash::message')

        {!! Form::open(['route'=>['ticket.post'], 'method' => 'post' ]) !!}

        <div class="form-group {{ $errors->has('text') ? ' has-error' : '' }}">
            {!! Form::label('text', 'متن پیغام:') !!}
            {!! Form::textarea('text', null, ['class' => 'form-control', 'id' => 'editorcm']) !!}
            @if ($errors->has('text'))
                <span class="help-block"><strong>{{ $errors->first('text') }}</strong></span>
            @endif
        </div>

        <button class="btn btn-success">ارسال پیغام</button>

        {!! Form::close() !!}

    </div>
    <div class="clearfix"></div>

    <div>@include('partials.miniFooter')</div>

@endsection
@push('scripts')
    <script type="text/javascript" src="{{ asset('editor/basic/ckeditor/ckeditor.js') }}"></script>
    <script type="text/javascript" src="{{ asset('editor/basic/ckeditor/adapters/jquery.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('textarea#editorcm').ckeditor();
            $('html, body').animate({
                scrollTop: $("#myDiv").offset().top
            }, 2000);
        });
    </script>
@endpush

resources/views/index/upload.blade.php
@extends('layouts.app')
@section('content')

    <section class="content-header">
        <h1 class="pull-left">صفحه آپلود</h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('products.create') !!}">لیست فایل ها</a>
        </h1>
    </section>

    <div class="content">
        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">

                @if(!Auth::check())
                    {{ die() }}
                @else
                    <br>
                    {{--        @can('is-writer')--}}

                    {{--@include('partials.header')--}}

                    {!! Form::open(['route'=>['upload.post' ], 'method' => 'post', 'files' => true ]) !!}

                    <input type="file" name="file1">
                    @if(isset($url1))
                        <div>{{ $url1 }}</div>@endif
                    <br>
                    <input type="file" name="file2">
                    @if(isset($url2))
                        <div>{{ $url2 }}</div>@endif
                    <br>
                    <input type="file" name="file3">
                    @if(isset($url3))
                        <div>{{ $url3 }}</div>@endif
                    <br>
                    <input type="file" name="file4">
                    @if(isset($url4))
                        <div>{{ $url4 }}</div>@endif
                    <br>
                    <input type="file" name="file5">
                    @if(isset($url5))
                        <div>{{ $url5 }}</div>@endif
                    <br>
                    <button type="submit" class="btn btn-primary">آپلود</button>

                    {!! Form::close() !!}

                    <br><br><br><br><br>
                    {{--@include('partials.footer')--}}

                    {{--@endcan--}}
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/index/usersProfile.blade.php
@extends('layouts.index')
@section('header')
    {{--    <link href="{{asset('css/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">--}}
    <link rel="stylesheet" href="{{ asset("bower_components/bootstrap/dist/css/bootstrap.min.css") }}">
    {{--    <link href="{{asset('css/bootstrap/css/bootstrap-responsive.min.css')}}" rel="stylesheet">--}}
    {{--<link href="{{asset('css/bootstrap/css/bootstrap-responsive-rtl.min.css')}}" rel="stylesheet">--}}
    <link rel="stylesheet" href="{{ asset("bower_components/bootstrap-rtl/dist/css/bootstrap-rtl.min.css") }}">
@endsection
@section('content')
    <div>
        @include('partials.miniHeader')
    </div>
    <div class="container" style="margin-top: 80px ">
        <div class="row">
            <div class="col-sm-12 ">
                <a href="{{route('ticket.get')}}"><span style="font-size: x-large">ارسال نامه به پشتیبانی</span></a>
                <p>برای ارسال نامه به پشتیبانی و یا پیگیری نامه قبلی کلیک کنید:
                    <a href="{{route('ticket.get')}}" class="btn btn-info btn-lg">
                        <span class="glyphicon glyphicon-envelope"></span> ارسال پیغام
                    </a>
                </p>
            </div>
        </div>
        <br>
        <hr>
        <br>
        <br>
        <br>
        <div style="font-size: large">لیست فاکتور ها:</div>
        @if(count($factors))
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>شماره فاکتور</th>
                    <th>نام شما</th>
                    <th style="max-width:350px">محصولات</th>
                    <th>مجموع</th>
                    <th>مجموع تخفیف ها</th>
                    <th>مبلغ قابل پرداخت</th>
                    <th>وضعیت پرداخت</th>
                    <th>پرداخت</th>
                </tr>
                </thead>
                <tbody>
                @foreach($factors as $factor)
                    <tr>
                        <td>{{$factor->id}}</td>
                        <td>{{$factor->user->name}}</td>
                        <td>
                            @foreach($factor->products as $product)
                            {{$product->title}}
                            <br>
                            {{$product->price}} -
                                تومان
                                <br>
                            @endforeach
                        </td>
                        <td>{{$factor->sum}}</td>
                        <td>{{$factor->discount_sum}}</td>
                        <td>{{$factor->sum - $factor->discount_sum}} <span> تومان </span></td>
                        @if($factor->is_paid == 0)
                            <td>پرداخت نشده</td>
                            <td>
                                {!! Form::open(['route'=>['pay.factor', 'factor_id' => $factor->id ], 'method' => 'post']) !!}
                                <button type="submit" class="btn btn-success"> پرداخت </button>
                                {!! Form::close() !!}
                            </td>
                        @else
                            <td>پرداخت شده</td>
                            <td>-</td>
                        @endif
                    </tr>
                @endforeach
                </tbody>
            </table>
        @else
            هنوز فاکتری برای شما صادر نشده است.
        @endif
        <br>
        <br>
        <br>
        <hr>
        <br>
        <br>
        <br>
        تنظیمات کاربری
        <a href="{{ route('profile.edit') }}" class="btn btn-default"> ویرایش </a>
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>نام کاربری:</td>
                <td>{{$user->name}}</td>
            </tr>
            <tr>
                <td>ایمیل:</td>
                <td>{{$user->email}}</td>
            </tr>
            <tr>
                <td>موجودی:</td>
                <td>{{$user->balance}}</td>
            </tr>
            </tbody>
        </table>
        <br>
    </div>
    <div class="clearfix"></div>
    <div style="height: 70px"></div>
    <div>@include('partials.miniFooter')</div>

@endsection

resources/views/index/usersProfileEdit.blade.php
@extends('layouts.index')
@section('header')
    {{--    <link href="{{asset('css/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">--}}
    <link rel="stylesheet" href="{{ asset("bower_components/bootstrap/dist/css/bootstrap.min.css") }}">
    {{--    <link href="{{asset('css/bootstrap/css/bootstrap-responsive.min.css')}}" rel="stylesheet">--}}
    {{--<link href="{{asset('css/bootstrap/css/bootstrap-responsive-rtl.min.css')}}" rel="stylesheet">--}}
    <link rel="stylesheet" href="{{ asset("bower_components/bootstrap-rtl/dist/css/bootstrap-rtl.min.css") }}">
@endsection
@push('header')
    <style>
        label{
            margin-top: 10px;
        }
    </style>
@endpush
@section('content')
    @include('partials.miniHeader')

    <div class="row">
        <div class="col-sm-3 col-sm-offset-3">

            {!! Form::open(['route'=>['profile.post', $user->id ] ]) !!}

            <label for="name">نام:</label>
            <input id="name" type="text" name="name" class="form-control" value="{{ $user->name }}">

            <label for="email">ایمیل:</label>
            <input id="email" type="text" name="email" class="form-control" value="{{ $user->email }}">

            <label for="password">رمز عبور:</label>
            <input id="password" type="password" name="password" class="form-control">

            <label for="password_retype">تکرار رمز عبور:</label>
            <input id="password_retype" type="password" name="password_retype" class="form-control" >
            <br>
            <button type="submit" class="btn btn-success">ذخیره</button>
            <br>
            <br>
            <span style="color: red">*</span>
            <span>درصورتی که نمیخواید رمز عبور خود را تغییر دهید قسمت رمز عبور را خالی بگذارید.</span>

            {!! Form::close() !!}

        </div>
    </div>

    <div style="height: 70px"></div>
    <div>@include('partials.miniFooter')</div>

@endsection